#!/usr/bin/env python

"""
This will work in development on a relative folder basis
It will then work when installed in site-packages on a target system
where the runner script is in /usr/bin (or wherever)
"""
from sdk.softfire.main import start_manager
from eu.softfire.SecurityManager import SecurityManager

import os

def start():
    os.environ["http_proxy"] = ""
    #print(os.environ["http_proxy"])
    #print(os.environ["no_proxy"])
    sec_man = SecurityManager()
    start_manager(sec_man, 'etc/security-manager.ini')


if __name__ == '__main__':
    start()

