#!/usr/bin/env python

"""
This will work in development on a relative folder basis
It will then work when installed in site-packages on a target system
where the runner script is in /usr/bin (or wherever)
"""
from sdk.softfire.main import start_manager
from eu.softfire.SecurityManager import SecurityManager, UpdateStatusThread
#from eu.softfire.Api import Api

import asyncio
import os
from concurrent.futures import ProcessPoolExecutor
from eu.softfire.utils.utils import config_path

def start():
    os.environ["http_proxy"] = ""
    #print(os.environ["http_proxy"])
    #print(os.environ["no_proxy"])
    #sec_man = SecurityManager(get_logger("eu.softfire.security-manager"))
    #executor = ProcessPoolExecutor(1)
    sec_manager = SecurityManager(config_path)
    thread = UpdateStatusThread(sec_manager)
    thread.start()

    start_manager(sec_manager)
    #asyncio.ensure_future(loop.run_in_executor(executor, Api.start))


if __name__ == '__main__':
    start()

