#!/usr/bin/env python

"""
This will work in development on a relative folder basis
It will then work when installed in site-packages on a target system
where the runner script is in /usr/bin (or wherever)
"""
from sdk.softfire.main import start_manager
from eu.softfire.sec.SecurityManager import SecurityManager, UpdateStatusThread
import eu.softfire.sec.Api as api
from multiprocessing import Process

import asyncio
from concurrent.futures import ProcessPoolExecutor
import os
from eu.softfire.sec.utils.utils import config_path

def start():
    os.environ["http_proxy"] = ""

    sec_manager = SecurityManager(config_path)
    thread = UpdateStatusThread(sec_manager)
    thread.start()
    api.StartThread().start()

    start_manager(sec_manager)


if __name__ == '__main__':
    start()

